// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2a-wfdUm1Ebj2YejsI8PMVm9oq1ryaBo',
    appId: '1:846678971915:web:522c995592bcb457b4190e',
    messagingSenderId: '846678971915',
    projectId: 'bluflix-tg',
    authDomain: 'bluflix-tg.firebaseapp.com',
    storageBucket: 'bluflix-tg.firebasestorage.app',
    measurementId: 'G-ZZLEKQX879',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAccdNaGd1KFs1ptgfqYt3tVLCLmvPVw',
    appId: '1:846678971915:android:dd3925f1bb6e571fb4190e',
    messagingSenderId: '846678971915',
    projectId: 'bluflix-tg',
    storageBucket: 'bluflix-tg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJNOuSlaxiJu5N_42QAYlhj1URs1aH3U',
    appId: '1:846678971915:ios:55ab5220641a87e2b4190e',
    messagingSenderId: '846678971915',
    projectId: 'bluflix-tg',
    storageBucket: 'bluflix-tg.firebasestorage.app',
    iosClientId: '846678971915-em7sm5na57d66eraapke1g9vt2odpmq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJNOuSlaxiJu5N_42QAYlhj1URs1aH3U',
    appId: '1:846678971915:ios:55ab5220641a87e2b4190e',
    messagingSenderId: '846678971915',
    projectId: 'bluflix-tg',
    storageBucket: 'bluflix-tg.firebasestorage.app',
    iosClientId: '846678971915-em7sm5na57d66eraapke1g9vt2odpmq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2a-wfdUm1Ebj2YejsI8PMVm9oq1ryaBo',
    appId: '1:846678971915:web:53edbcd009bd4b8ab4190e',
    messagingSenderId: '846678971915',
    projectId: 'bluflix-tg',
    authDomain: 'bluflix-tg.firebaseapp.com',
    storageBucket: 'bluflix-tg.firebasestorage.app',
    measurementId: 'G-3YE61WVLYM',
  );
}
